### ISSUE TITLE
Error updating CDEs

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-cadsr-tools#17]
Investigate error with CDE import.

```
02:04:47.919 INFO  o.m.c.ingestor.util.CedarServices - 11400/70886 CDEs retrieved.
02:04:48.878 INFO  o.m.c.ingestor.util.CedarServices - 11500/70886 CDEs retrieved.
02:04:49.746 INFO  o.m.c.ingestor.util.CedarServices - 11600/70886 CDEs retrieved.
02:04:50.663 INFO  o.m.c.ingestor.util.CedarServices - 11700/70886 CDEs retrieved.
02:04:51.775 ERROR o.m.c.i.t.c.CadsrCategoriesAndCdesUpdaterTool - Error: Server returned HTTP response code: 500 for URL: https://resource.metadatacenter.org/folders/https%3A%2F%2Frepo.metadatacenter.org%2Ffolders%2F1ee5ef41-0605-4c18-9054-b01eb4290339/contents-extract?resource_types=field&field_names=schema:identifier,pav:version,sourceHash,categories&offset=11700&limit=100
java.io.IOException: Server returned HTTP response code: 500 for URL: https://resource.metadatacenter.org/folders/https%3A%2F%2Frepo.metadatacenter.org%2Ffolders%2F1ee5ef41-0605-4c18-9054-b01eb4290339/contents-extract?resource_types=field&field_names=schema:identifier,pav:version,sourceHash,categories&offset=11700&limit=100
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.metadatacenter.cadsr.ingestor.util.CedarServices.findCdeSummariesInFolder(CedarServices.java:123)
	at org.metadatacenter.cadsr.ingestor.util.CdeUtil.getExistingCedarCdeSummaries(CdeUtil.java:133)
	at org.metadatacenter.cadsr.ingestor.tools.cde.CadsrCategoriesAndCdesUpdaterTool.main(CadsrCategoriesAndCdesUpdaterTool.java:172)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://resource.metadatacenter.org/folders/https%3A%2F%2Frepo.metadatacenter.org%2Ffolders%2F1ee5ef41-0605-4c18-9054-b01eb4290339/contents-extract?resource_types=field&field_names=schema:identifier,pav:version,sourceHash,categories&offset=11700&limit=100
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.metadatacenter.cadsr.ingestor.util.CedarServices.findCdeSummariesInFolder(CedarServices.java:106)
	... 4 more
```

**Comment by martinjoconnor** [comment]
Looks like a transient error with Redis that has happened only once. Will look more deeply if it happens again.

**Comment by martinjoconnor** [comment]
Now reoccurs every time the caDSR ingest script is executed.

**Comment by martinjoconnor** [comment]
Worker server had broken connection to Redis so stopped processing logs, which then kept growing. Restarted it.

Will monitor next run of caDSR ingestor.

**Comment by martinjoconnor** [comment]
Broken Redis connection was source of issue
